// src/app/terms/page.tsx — Terms of Service page

import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Kaamly",
  description: "Terms of Service for Kaamly – AI-powered job application platform",
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[var(--color-background)] text-[var(--color-foreground)] px-4 py-16">
      <div className="max-w-3xl mx-auto space-y-8">
        <Link
          href="/"
          className="text-sm text-[var(--color-primary)] hover:underline"
        >
          ← Back to Home
        </Link>

        <h1 className="font-display text-3xl font-bold text-[var(--color-primary)]">
          Terms of Service
        </h1>
        <p className="text-sm text-[var(--color-muted-foreground)]">
          Last updated: March 16, 2026
        </p>

        <section className="space-y-4 text-[var(--color-foreground)] leading-relaxed">
          <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Kaamly (&quot;the Service&quot;), you agree to be bound by these
            Terms of Service. If you do not agree, please do not use the Service.
          </p>

          <h2 className="text-xl font-semibold">2. Description of Service</h2>
          <p>
            Kaamly is an AI-powered job application management platform that helps users
            generate outreach emails, track applications, and manage their job search process.
          </p>

          <h2 className="text-xl font-semibold">3. Account &amp; Authentication</h2>
          <p>
            You sign in using your Google account. You are responsible for maintaining the
            security of your account. We are not liable for any unauthorized access resulting
            from your failure to protect your credentials.
          </p>

          <h2 className="text-xl font-semibold">4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Use the Service for spam or unsolicited bulk emails</li>
            <li>Misrepresent your identity or qualifications</li>
            <li>Attempt to access other users&apos; data</li>
            <li>Use the Service in violation of any applicable laws</li>
          </ul>

          <h2 className="text-xl font-semibold">5. AI-Generated Content</h2>
          <p>
            Emails and content generated by our AI are suggestions only. You are solely
            responsible for reviewing and approving all content before sending. We do not
            guarantee the accuracy or appropriateness of AI-generated output.
          </p>

          <h2 className="text-xl font-semibold">6. Gmail Integration</h2>
          <p>
            When you connect Gmail, you authorize Kaamly to send emails on your behalf.
            You can revoke this permission at any time. We do not read or store your inbox
            contents beyond what is necessary to provide the Service.
          </p>

          <h2 className="text-xl font-semibold">7. Data &amp; Privacy</h2>
          <p>
            Your use of the Service is also governed by our{" "}
            <Link href="/privacy" className="text-[var(--color-primary)] underline">
              Privacy Policy
            </Link>. Please review it to understand our data practices.
          </p>

          <h2 className="text-xl font-semibold">8. Limitation of Liability</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable
            for any damages arising from your use of the Service, including but not limited to
            lost opportunities, rejected applications, or email delivery failures.
          </p>

          <h2 className="text-xl font-semibold">9. Modifications</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the
            Service after changes constitutes acceptance of the new terms.
          </p>

          <h2 className="text-xl font-semibold">10. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a
              href="mailto:anikeshuzumaki@gmail.com"
              className="text-[var(--color-primary)] underline"
            >
              anikeshuzumaki@gmail.com
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
